steps:
  - name: "Release"
    image: gcr.io/kaniko-project/executor:latest
    branch: master
    args:
      - "--dockerfile=/app/Dockerfile"
      - "--context=dir:///app"
      - "--cache=true"
      - "--cache-repo jordanph/kubes-sidecar-cache"
      - "--destination=jordanph/kubes-sidecar:latest"
    mountSecret:
      - name: docker-config
        mountPath: /kaniko/.docker
